# Generated by Django 4.0.4 on 2022-06-30 09:26

import apps.content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=apps.content.models.upload_to),
        ),
    ]
