# Generated by Django 4.0.4 on 2022-10-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='content.picture'),
        ),
    ]
